<a href="https://colab.research.google.com/github/kaviyakesavan/datascienceprojects/blob/main/Project1(DS).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# @title PROJECT 1
# analysing IMDB Movie dataset
import pandas as pd
df = pd.read_csv("/content/IMDBMovie (1).csv")
df

,ID,Title,Genre,Director,Year,Runtime_minutes,Rating,Votes,Revenue_millions
0,1,Guardians of the Galaxy,Action,James Gunn,2014,121,8.1,757074,333.13
1,2,Prometheus,Adventure,Ridley Scott,2012,124,7.0,485820,126.46
2,3,Split,Horror,M. Night Shyamalan,2016,117,7.3,157606,138.12
3,4,Sing,Animation,Christophe Lourdelet,2016,108,7.2,60545,270.32
4,5,Suicide Squad,Action,David Ayer,2016,123,6.2,393727,325.02
...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,Crime,Billy Ray,2015,111,6.2,27585,NaN
996,997,Hostel: Part II,Horror,Eli Roth,2007,94,5.5,73152,17.54
997,998,Step Up 2: The Streets,Drama,Jon M. Chu,2008,98,6.2,70699,58.01
998,999,Search Party,Adventure,Scot Armstrong,2014,93,5.6,4881,NaN
999,1000,Nine Lives,Comedy,Barry Sonnenfeld,2016,87,5.3,12435,19.64

In [ ]:
# @title Task 1
# how many rows are there in the IMDB dataset
df.shape[0]

1000

In [ ]:
# @title Task 2
# what ist the 75th percentile of rating in the imdb dataset?
df.describe()

,ID,Year,Runtime_minutes,Rating,Votes,Revenue_millions
count,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,872.000000
mean,500.500000,2012.783000,113.172000,6.723200,1.698083e+05,82.956376
std,288.819436,3.205962,18.810908,0.945429,1.887626e+05,103.253540
min,1.000000,2006.000000,66.000000,1.900000,6.100000e+01,0.000000
25%,250.750000,2010.000000,100.000000,6.200000,3.630900e+04,13.270000
50%,500.500000,2014.000000,111.000000,6.800000,1.107990e+05,47.985000
75%,750.250000,2016.000000,123.000000,7.400000,2.399098e+05,113.715000
max,1000.000000,2016.000000,191.000000,9.000000,1.791916e+06,936.630000

In [ ]:
# @title Task 3
#how many NA values are there in the field "Revenue"?
df["Revenue_millions"].isnull().sum()

128

In [ ]:
# @title Task 4
#how many movies have  revenue higher than 75 million?
(df['Revenue_millions'] > 75).sum()
df[df["Revenue_millions"]>75]["Revenue_millions"].count()

318

In [ ]:
# @title Task 5
# How many movies have revenue greater than 50 million but rating less than 7?
df[(df['Revenue_millions'] > 50) & (df['Rating'] < 7)]['Title'].count()

211

In [ ]:
# @title Task 6
# what is the total Revenue genarated by movies in the year 2015 ?
df[df["Year"] == 2015]["Revenue_millions"].sum()

8854.119999999999

In [ ]:
# @title Task 7
# What is the average rating for the genre adventure in the year 2015?
df[(df["Year"] == 2015) & (df["Genre"] == "Adventure")]["Rating"].mean()

6.8

In [ ]:
# @title Task 8
# What is the average duration of movies in rows 75 to 150? Please note that the rows in python start from 0.
df.loc[75:150]["Runtime_minutes"].mean()

127.47368421052632

In [ ]:
# @title Task 9
# Which year generated the highest revenue?
df['Revenue_millions'].max()
df[df['Revenue_millions']== 936.63 ]["Year"]
df.sort_values(by = "Revenue_millions", ascending = False)

,ID,Title,Genre,Director,Year,Runtime_minutes,Rating,Votes,Revenue_millions
50,51,Star Wars: Episode VII - The Force Awakens,Action,J.J. Abrams,2015,136,8.1,661608,936.63
87,88,Avatar,Action,James Cameron,2009,162,7.8,935408,760.51
85,86,Jurassic World,Action,Colin Trevorrow,2015,124,7.0,455169,652.18
76,77,The Avengers,Action,Joss Whedon,2012,143,8.1,1045588,623.28
54,55,The Dark Knight,Action,Christopher Nolan,2008,152,9.0,1791916,533.32
...,...,...,...,...,...,...,...,...,...
977,978,Amateur Night,Comedy,Lisa Addario,2016,92,5.0,2229,NaN
978,979,It's Only the End of the World,Drama,Xavier Dolan,2016,97,7.0,10658,NaN
988,989,Martyrs,Horror,Pascal Laugier,2008,99,7.1,63785,NaN
995,996,Secret in Their Eyes,Crime,Billy Ray,2015,111,6.2,27585,NaN
998,999,Search Party,Adventure,Scot Armstrong,2014,93,5.6,4881,NaN

In [ ]:
# @title Task 10
# What is the maximum revenue out of (10,20,30,40,50) rows]
df.drop([10,20,30,40,50],axis =0)["Revenue_millions"].max()

760.51

In [ ]:
# @title Task 11
# How many movies with the genres â€˜Adventureâ€™, â€˜Actionâ€™, â€˜Horrorâ€™, and â€˜Crimeâ€™ exist in the IMDB dataset?
cond = df[df['Genre'].isin(['Adventure','Action','Horror','Crime'])]['Title'].count()
cond

485

In [ ]:
# @title Task 12
# Create a genre-level report with metrics average rating, the average number of votes, and average revenue.
# What is the average rating of the â€˜Horrorâ€™ genre?
df[df["Genre"] == "Horror"]["Rating"].mean()

5.867391304347826

In [ ]:
# @title Task 13
# How many movies has Billy Ray	directed and find the year of release of those movies
df[df["Director"] == 'Billy Ray'].sum()

ID                                   996
Title               Secret in Their Eyes
Genre                              Crime
Director                       Billy Ray
Year                                2015
Runtime_minutes                      111
Rating                               6.2
Votes                              27585
Revenue_millions                     0.0
dtype: object

In [ ]:
# @title Task 14
# How many movies were released in the year 2012 - 14. What type of genre were released the most
cond = df[df['Year'].isin([2012,2013,2014])]['Year'].count()
print("No.Of Movies released in the year 2012 - 14 were",cond)
cond1 = df[df['Year'].isin([2012,2013,2014])]['Genre']
print("Type of genre were released the most",cond1.max())

No.Of Movies released in the year 2012 - 14 were 253
Type of genre were released the most Thriller

In [ ]:
# @title Task 15
# Which Movie had the highest vote and what genre it belongs to.
print(df[df['Votes']== df["Votes"].max()]['Title'])
df[df['Votes']== df["Votes"].max()]['Genre']

54    The Dark Knight
Name: Title, dtype: object

54    Action
Name: Genre, dtype: object

In [ ]:
# @title Task 16
# Find the Director whose movie grossed the highest. Also find the total revenue generated by that director
cond = df[df['Revenue_millions'] == df['Revenue_millions'].max()]['Director']
print("Director whose movie grossed the highest is",cond)
cond1 = df[df["Director"]== 'J.J. Abrams']["Revenue_millions"].sum()
print("Total Revenue generated by JJ Abrams", cond1)

Director whose movie grossed the highest is 50    J.J. Abrams
Name: Director, dtype: object
Total Revenue generated by JJ Abrams 1683.4499999999998

In [ ]:
# @title Task 17
'''
Create a report to showcase the revenue of each movie, as % revenue concerning the total revenue of the respective genre and year of the movie.

For example if a movie â€˜ABCâ€™ has genre â€˜Actionâ€™ and released in 2015, then % revenue will be

- (Revenue of the movie â€˜ABCâ€™ *100)/ (Total revenue of the genre â€˜Actionâ€™ in 2015)

 What is the  % revenue of the movie â€˜Splitâ€™ in its respective genre and year?


Hint:

Create a dataset which has revenue for each genre within a year
Rename the column as â€˜Total_revenueâ€™
Merge the dataset with cleaned dataset so that total revenue is mapped to each movie
Just apply percent formula using apply(lamda)
  Revenue of movie * 100 / (Total revenue of genre and year)


Query the merged dataset for â€˜Splitâ€™ movie
'''

'\nCreate a report to showcase the revenue of each movie, as % revenue concerning the total revenue of the respective genre and year of the movie.\n\nFor example if a movie â€˜ABCâ€™ has genre â€˜Actionâ€™ and released in 2015, then % revenue will be\n\n- (Revenue of the movie â€˜ABCâ€™ *100)/ (Total revenue of the genre â€˜Actionâ€™ in 2015)\n\n What is the  % revenue of the movie â€˜Splitâ€™ in its respective genre and year?\n\n\nHint:\n\nCreate a dataset which has revenue for each genre within a year\nRename the column as â€˜Total_revenueâ€™\nMerge the dataset with cleaned dataset so that total revenue is mapped to each movie\nJust apply percent formula using apply(lamda)\n  Revenue of movie * 100 / (Total revenue of genre and year)\n\n\nQuery the merged dataset for â€˜Splitâ€™ movie\n'